### ISSUE TITLE
Doesn't flash With my MacBook Air 2018

### ISSUE THREAD

**Issue by Git4Manohar** [MySPELEC/S.ODI_ultra#1]
I'm trying to flash basic AnalogOut LEDCSoftwareFade but it's throwing me a fatal error.
I tried to resolve it by changing my USB Cables but it didn't work.
Kindly help me in resolving this issue.
Thanks and regards

**Comment by SudhaMaanasa** [comment]
Try installing its drivers... 
For Windows, [https://www.driverscape.com/download/usb-serial-ch340](url)
For MAC, [https://github.com/adrianmihalko/ch340g-ch34g-ch34x-mac-os-x-driver](url)
Sometimes it may be due to insufficient voltage to the COM port. For COM port to work properly u will need a 5v supply. So, try to upload while charging ur pc.

**Comment by Git4Manohar** [comment]
> Try installing its drivers...
> For Windows, [https://www.driverscape.com/download/usb-serial-ch340](url)
> For MAC, [https://github.com/adrianmihalko/ch340g-ch34g-ch34x-mac-os-x-driver](url)
> Sometimes it may be due to insufficient voltage to the COM port. For COM port to work properly u will need a 5v supply. So, try to upload while charging ur pc.

Thanks it worked for me. I have installed the drivers and started charging the laptop while flashing.
